name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "infopost-test"
          heroku_email: "934s4rn9+heroku@posteo.de"
          procfile: "web: gunicorn app:application"
        env:
          NAME: "Tom"a
